# -*- coding: utf-8 -*-
"""history.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wFBc8Iqld4I4q6X0hKa3tk0dCQ6RCDYP
"""

import csv
message_list = []


def write_empty_row(filename="history.csv"):
    with open(filename, "a") as file:
        writer = csv.writer(file)
        writer.writerow("")


def write_message(datetime_mes, who, message, filename="history.csv"):
    with open(filename, "a", newline="") as file:
        writer = csv.writer(file)
        writer.writerow((datetime_mes, who, message))

if __name__ == "__main__":
    write_message("12/12/22 09:03:04", "Mary", "HOHsadasd")
    write_empty_row()
    write_message("12/12/22 09:03:04", "Mary", "HOHOHO")
    write_empty_row()
    write_message("12/12/22 09:03:04", "Mary", "HOHOHO")